name: Lint proto files

on:
  push:
    branches: [chain4travel, dev]
  pull_request:
    tags-ignore: ["*"]  
    branches: [chain4travel, dev]

permissions:
  contents: read

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
