name: Build Docker Image

on:
  pull_request:  
    branches: [chain4travel, dev]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build docker image
        run: scripts/build_local_image.sh
