name: Test e2e

on:
  workflow_run:
    workflows: ["CNR - Build + test + release"]
    types:
      - completed

permissions:
  contents: read

jobs:
  test_e2e:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build the caminogo binaries
        shell: bash
        run: ./scripts/build.sh
      - name: Run e2e tests
        shell: bash
        run: scripts/tests.e2e.sh ./build/camino-node ./tools/camino-network-runner/bin/camino-network-runner